ALTER TABLE tasks
DROP COLUMN owner;
     
ALTER TABLE tasks
ADD COLUMN user_id INT,
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tasks
ADD CONSTRAINT tasks_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
